name: Generate JWT Keys
description: Setup Python and generate local RSA keys for compose-based jobs
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt
          services/auth/requirements.txt
          services/tasks/requirements.txt
          services/frontend/requirements.txt
          gateway/requirements.txt
    - shell: bash
      run: python -m pip install --upgrade pip
    - shell: bash
      run: pip install cryptography
    - shell: bash
      run: python keys/generate.py
